services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    image: adityaisme/orchestrator:latest
    env_file:
      - .env.production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - mock-network
    restart: unless-stopped

  nginx:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - orchestrator
    networks:
      - mock-network
    restart: unless-stopped

networks:
  mock-network:
    driver: bridge